version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: locations-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: locations_db
      MYSQL_USER: locations_user
      MYSQL_PASSWORD: locations_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: